<?= $arenda['content'] ?>
<? return 1 ?>

<? if(isset($_slider)) { ?>
    <div class="big_img2">
     <div <? if($isSlider) { ?>id="slider" class="nivoSlider"<? } ?>>
        <? foreach($_slider as $row) if(empty($row['link'])) { ?>
            <img src="<?=$row['image'] ?>" width="774" height="348" alt="<?=$row['title'] ?>" />
        <? } else { ?>
            <a href="<?=$row['link'] ?>"><img src="<?=$row['image'] ?>" width="774" height="348" alt="<?=$row['title'] ?>" /></a>
        <? } ?>
     </div>
    </div>
<? } ?>
<? if(isset($_yachts)) {
    $count = count($_yachts); ?>
<? if($count>3 and !empty($arenda['yachtsListHeader'])) { ?>
    <p class="vk_arenda"><?=$arenda['yachtsListHeader'] ?></p>
    <div class="vkladki" style="margin-top:45px;">
<? } else { ?>
    <div class="vkladki" style="margin-top:35px;">
            <p class="vk_arenda"><?=$arenda['yachtsListHeader'] ?></p>
<? } ?>
            <ul class="vk2 vk_margin_<?=$count ?>" id="tabsList">
            <? foreach($_type as $id=>$row) if(isset($_yachts[$id])) { ?>
                <li <? if(isset($row['sel'])) { ?>id="v_active"<? } ?>><a name="yachts<?=$id ?>"><p><span><?=$row['name'] ?></span></p></a></li>
            <? } ?>
            </ul>
    </div>

    <div class="spacer"></div>
    <? foreach($_type as $id=>$type) { ?>
    <div id="yachts<?=$id ?>" class="tabsList <? if(!isset($type['sel'])) { ?>cmfHide<? } ?>">
        <div id="scroll_vertical" style="max-height:850px;"><div>
        <? if(isset($_yachts[$id])) { ?>
        <? foreach($_yachts[$id] as $list) { ?>
            <? $i = 0; foreach($list as $row) { ?>
            <div class="block_yachts <?= $i++==2 ? 'last_yacht' : '' ?>">
                <p class="yacht_name"><?=$row['name'] ?></p>
		<div class="plusbuttblock"><span><g:plusone size="small" href="<?=$row['url'] ?>" count="false"></g:plusone></span><span class="like">Мне нравится</span></div>
                <a href="<?=$row['url'] ?>" class="yacht_img"><span class="rec_more">&nbsp;</span><img src="<?=$row['image'] ?>" alt="<?=$row['title'] ?>" title='<?=$row['title'] ?>'/></a>

                <p class="yacht_size">Длина: <span><?=$row['param1'] ?></span></p>
                <p class="yacht_size">Max. пассажиров: <span><?=$row['param2'] ?> чел</span></p>

                <p class="price">Стоимость аренды:</p>
                <p class="price2">час: <span><img src="images/y_sel.gif" alt="" /> <?=$row['priceHour'] ?></span></p>
                <p class="price2">12 часов: <span><img src="images/y_sel.gif" alt="" /> <?=$row['priceLightDay'] ?></span></p>
                <p class="price2">сутки: <span><img src="images/y_sel.gif" alt="" /> <?=$row['priceDay'] ?></span></p>
                <p class="price2">неделя: <span><img src="images/y_sel.gif" alt="" /> <?=$row['priceWeek'] ?></span></p>
                <a href="<?=$row['url'] ?>" class="yacht_link"></a>
                <p class="yachts_phone"><?=$phone1 ?> <span><?=$phone2 ?></span></p>
            </div>
            <? } ?>
            <div class="spacer"></div>

        <? } ?>
        <? } ?>
        </div></div>
    </div>
   	<? } ?>
    <script>
    cmf.main.scroll.initFull('yachts');
    </script>
<? } ?>
        <div class="spacer"></div>

    <div class="text_block3">
        <?=$arenda['content'] ?>
    </div>

