
<? if(isset($_yachts)) { ?>
    <div class="vkladki" style="margin-top:35px;">
            <ul class="vk2 vk_margin_<?=count($_type) ?>" id="tabsList">
            <? foreach($_type as $id=>$row) { ?>
                <li <? if(isset($row['sel'])) { ?>id="v_active"<? } ?>><a name="yachts<?=$id ?>"><p><span><?=$row['name'] ?></span></p></a></li>
            <? } ?>
            </ul>
    </div>

    <? foreach($_type as $id=>$type) { ?>
    <div id="yachts<?=$id ?>" class="tabsList <? if(!isset($type['sel'])) { ?>cmfHide<? } ?>">
        <div id="scroll_vertical" style="max-height:550px;"><div>
        <? if(isset($_yachts[$id])) { ?>
        <? foreach($_yachts[$id] as $list) { ?>
            <? $i = 0; foreach($list as $row) { ?>
            <div class="block_yachts <?= $i++==2 ? 'last_yacht' : '' ?>">
                <p class="yacht_name"><?=$row['name'] ?></p>
                <a href="<?=$row['url'] ?>" class="yacht_img"><span class="rec_more">&nbsp;</span><img src="<?=$row['image'] ?>" alt="<?=$row['title'] ?>" title='<?=$row['title'] ?>'/></a>

                <p class="yacht_size">Длина: <span><?=$row['param1'] ?></span></p>
                <p class="yacht_size">Max. пассажиров: <span><?=$row['param2'] ?> чел</span></p>

                <p class="price">Стоимость аренды:</p>
                <p class="price2">час: <span><img src="images/y_sel.gif" alt="" /> <?=$row['priceHour'] ?></span></p>
                <p class="price2">сутки: <span><img src="images/y_sel.gif" alt="" /> <?=$row['priceDay'] ?></span></p>
                <p class="price2">неделя: <span><img src="images/y_sel.gif" alt="" /> <?=$row['priceWeek'] ?></span></p>
                <a href="<?=$row['url'] ?>" class="yacht_link"></a>
            </div>
            <? } ?>
            <div class="spacer"></div>
        <? } ?>
        <? } ?>
        </div></div>
    </div>
   	<? } ?>
    <script>
    cmf.main.scroll.initFull('yachts');
    </script>
<? } ?>