<script type="text/javascript">
    window.___gcfg = {lang: 'ru'};
    (function () {
        var po = document.createElement('script');
        po.type = 'text/javascript';
        po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(po, s);
    })();
</script>
<?php
$error = "";
//if (strpos($metas, '<title>404') !== false) {
if (defined('IS_404_STATUS')) {
    $error = "_gaq.push(['_trackPageview', '/404.html?page=' + document.location.pathname + document.location.search + '&from;=' + document.referrer + '&etype;=missingcategory]);";
}
echo
"
<script type=\"text/javascript\">
var _gaq = _gaq || [];
_gaq.push (['_setAccount', 'UA-4449273-7']);
_gaq.push (['_addOrganic', 'yandex.ru', 'query']);
_gaq.push (['_addOrganic', 'images.yandex.ru', 'text']);
_gaq.push (['_addOrganic', 'blogs.yandex.ru', 'text']);
_gaq.push (['_addOrganic', 'video.yandex.ru', 'text']);
_gaq.push (['_addOrganic', 'mail.ru', 'q']);
_gaq.push (['_addOrganic', 'go.mail.ru', 'q']);
_gaq.push (['_addOrganic', 'google.com.ua', 'q']);
_gaq.push (['_addOrganic', 'images.google.ru', 'q']);
_gaq.push (['_addOrganic', 'maps.google.ru', 'q']);
_gaq.push (['_addOrganic', 'rambler.ru', 'words']);
_gaq.push (['_addOrganic', 'nova.rambler.ru', 'query']);
_gaq.push (['_addOrganic', 'nova.rambler.ru', 'words']);
_gaq.push (['_addOrganic', 'gogo.ru', 'q']);
_gaq.push (['_addOrganic', 'nigma.ru', 's']);
_gaq.push (['_addOrganic', 'search.qip.ru', 'query']);
_gaq.push (['_addOrganic', 'webalta.ru', 'q']);
_gaq.push (['_addOrganic', 'sm.aport.ru', 'r']);
_gaq.push (['_addOrganic', 'meta.ua', 'q']);
_gaq.push (['_addOrganic', 'search.bigmir.net', 'z']);
_gaq.push (['_addOrganic', 'search.i.ua', 'q']);
_gaq.push (['_addOrganic', 'index.online.ua', 'q']);
_gaq.push (['_addOrganic', 'web20.a.ua', 'query']);
_gaq.push (['_addOrganic', 'search.ukr.net', 'search_query']);
_gaq.push (['_addOrganic', 'search.com.ua', 'q']);
_gaq.push (['_addOrganic', 'search.ua', 'q']);
_gaq.push (['_addOrganic', 'poisk.ru', 'text']);
_gaq.push (['_addOrganic', 'go.km.ru', 'sq']);
_gaq.push (['_addOrganic', 'liveinternet.ru', 'ask']);
_gaq.push (['_addOrganic', 'gde.ru', 'keywords']);
_gaq.push (['_addOrganic', 'affiliates.quintura.com', 'request']);
_gaq.push (['_addOrganic', 'akavita.by', 'z']);
_gaq.push (['_addOrganic', 'search.tut.by', 'query']);
_gaq.push (['_addOrganic', 'all.by', 'query']);
_gaq.push (['_trackPageview']);\n
" . $error . "\n
(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>";
?>