<div id="container">
    <div id="navigation-menu">
        <? if (!empty($mMenu)) { ?>
            <? if (isset($mMenu['isBoard'])) { ?>
                <a class="mybutton" href="<?= $boardAdd ?>"><?= word('Добавить объявление') ?></a>
            <? } ?>
            <i class="fa fa-bars"></i>
            <ul>
                <? if (!empty($mBMenu)) { ?>

                    <? foreach ($mBMenu as $row) { ?>
                        <li <? if (isset($row['sel'])) { ?>class="last"<? } ?>>
                            <a href="<?= $row['url'] ?>" title="<?= $row['title'] ?>" ><?= $row['name'] ?></a>
                        </li>
                    <? } ?>
                    <li class="navigation-sep"></li>
                <? } ?>
                <?
                foreach ($mMenu as $row)
                    if ($row) {
                        ?>
                        <li <? if (isset($row['sel'])) { ?>class="last"<? } ?>>
                            <a href="<?= $row['url'] ?>" title="<?= $row['title'] ?>" ><?= $row['name'] ?></a>
                        </li>
                    <? } ?>
                <? if (isset($mMenu['isBoard'])) { ?>
                    <li>
                        <a href="<?= $boardAdd ?>"><?= word('Добавить объявление') ?></a>
                    </li>
                <? } ?>
            </ul>
        <? } ?>
        <div class="clear"></div>
    </div>
    <div id="wrapper">
        <div id="content">
            <?= cmfMenu::viewSubMenu() ?>
            <? if (!cmfPages::isBlog()) { ?>
                <div class="gplus" style="float:right"><g:plusone ></g:plusone></div>
                    <? } ?>
                    <? if (isset($h1)) { ?>
                <h1><?= $h1 ?></h1>
            <? } ?>