
</div>

</div>
<div id="navigation" class="cmfHide1">
    <? if (!empty($mMenu)) { ?>
        <? if (!empty($mMenu)) { ?>
            <ul class="right-menu">
                <? if (!empty($mBMenu)) { ?>

                    <? foreach ($mBMenu as $row) { ?>
                        <li <? if (isset($row['sel'])) { ?>class="last"<? } ?>>
                            <a href="<?= $row['url'] ?>" title="<?= $row['title'] ?>" ><?= $row['name'] ?></a>
                        </li>
                    <? } ?>
                    <li class="navigation-sep"></li>
                <? } ?>
                <?
                foreach ($mMenu as $row)
                    if ($row) {
                        ?>
                        <li <? if (isset($row['sel'])) { ?>class="last"<? } ?>>
                            <a href="<?= $row['url'] ?>" title="<?= $row['title'] ?>" ><?= $row['name'] ?></a>
                        </li>
                    <? } ?>
            </ul>
        <? } ?>
    <? } ?>
    <div class="recommend cmfHide">
        <div class="h1"><?= word('Мы рекомендуем') ?></div>
        <?
        foreach ($yachtsList as $row) {
            list($page, $type, $id) = $row;
            if (isset($typeList[$page][$id]) and is_array($typeList[$page][$id])) {
                $row = $typeList[$page][$id];
                switch ($page) {
                    case 'arenda':
                        ?>
                        <div class="rent rent-arenda1">
                            <a href="<?= $row['url'] ?>" class="aboutyacht"></a>
                            <p><img src="<?= $row['image'] ?>" alt="<?= $row['title'] ?>" <?= $row['width'] ?>/></p>
                            <div class="name"><?= $row['name'] ?></div>
                            <div class="size"><?= $row['param1'] ?></div>
                            <? if (!empty($row['param2'])) { ?>
                                <div class="region"><?= $row['param2'] ?></div>
                            <? } ?>
                            <div class="type"></div>
                            <!--<div class="arendaPrice">Стоимость <br>аренды:</div>-->
                            <div class="price"><?= word('Цена за час') ?>: <?= $row['priceHour'] ?></div>
                            <? /*
                              <div class="price">
                              <?= word('час') ?>: <?= $row['priceHour'] ?>
                              <br><?= word('12 часов') ?>: <?= $row['priceLightDay'] ?>
                              <br><?= word('сутки') ?>: <?= $row['priceDay'] ?>
                              <br><?= word('неделя') ?>: <?= $row['priceWeek'] ?>
                              </div> */ ?>
                        </div>
                        <?
                        break;

                    case 'sale':
                        ?>
                        <div class="sale">
                            <a href="<?= $row['url'] ?>" class="aboutyacht"></a>
                            <p><img src="<?= $row['image'] ?>" alt="<?= $row['title'] ?>" <?= $row['width'] ?>/></p>
                            <div class="name"><?= $row['name'] ?></div>
                            <div class="size"><?= $row['param'] ?></div>
                            <div class="year"><?= word('Верфь') ?>: <?= $row['shipyards'] ?></div>
                            <div class="price"><?= word('Цена') ?>: <?= $row['price'] ?></div>
                            <div class="type"></div>
                        </div>
                        <?
                        break;

                    case 'brokerage':
                        ?>
                        <div class="sale">
                            <a href="<?= $row['url'] ?>" class="aboutyacht"></a>
                            <p><img src="<?= $row['image'] ?>" alt="<?= $row['title'] ?>" <?= $row['width'] ?>/></p>
                            <div class="name"><?= $row['name'] ?></div>
                            <div class="size"><?= $row['param2'] ?></div>
                            <div class="year"><?= word('Год') ?>: <?= $row['param'] ?></div>
                            <div class="price"><?= word('Цена') ?>: <?= $row['price'] ?></div>
                            <div class="type"></div>
                        </div>
                        <?
                        break;

                    default:
                        break;
                }
                ?>
            <? } ?>
        <? } ?>
    </div>
    <div class="social-networks">
        <h5><?= word('Социальные сети') ?> <i class="fa fa-bars"></i></h5>
        <div class="news-contents">
            <?= $networkR ?>
        </div>
    </div>
</div>
</div>