<?=$networkL?>
<div class="item-blog-article">
    <h1><?= $news['name'] ?></h1>
    <div class="meta-blog">
        <div class="meta-item"><img src="img/ico-date.png" alt="Дата публикации" title="Дата публикации"><?= $news['date'] ?></div>
        <div class="meta-item"><a href="<?= $row['url'] ?>" class="count-comment"><img src="img/ico-comments.png" alt="Количество комментариев" title="Количество комментариев"></a> <a href="<?= $row['url'] ?>#disqus_thread" data-disqus-identifier="blog<?=$news['id'] ?>" class="count-comment"></a></div>
        <div class="meta-item"><img src="img/ico-view.png" alt="Количество просмотров" title="Количество просмотров"> <span id="blogView<?=$news['id'] ?>"><?= $news['view'] ?></span></div>
        <div class="meta-blog-right">
            <div class="meta-item"><img src="img/ico-auther.png" alt="Автор" title="Автор"> <a href="<?= $autor['neturl'] ?>" target="_blank"><?= $autor['name'] ?></a></div>
        </div>
    </div>
    <? if (!empty($news['image'])) { ?>
        <p><a href="<?= $news['url'] ?>"><img src="<?= $news['image'] ?>" alt="<?= $news['title'] ?>" <?= $news['width'] ?>></a></p>
    <? } ?>
    <?= $news['content'] ?>

 <div id="disqus_thread"></div>



    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'nskyachts'; // required: replace example with your forum shortname
        var disqus_identifier = 'blog<?=$news['id'] ?>';
        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>

 <script type="text/javascript">
/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
var disqus_shortname = 'nskyachts'; // required: replace example with your forum shortname

/* * * DON'T EDIT BELOW THIS LINE * * */
(function () {
var s = document.createElement('script'); s.async = true;
s.type = 'text/javascript';
s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
(document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>
<script type="text/javascript">
(function () {
var s = document.createElement('script'); s.async = true;
s.type = 'text/javascript';
s.src = '<?=cmfBaseUrl ?>/controller/blog/view/?action=view&id=<?=$news['id'] ?>&'+ (new Date()).getMilliseconds();
(document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>