<h1 class="contactform-h1"><?= word('Восстановление пароля') ?></h1>
<div class="content-info">
    <?= $content ?>
</div>
<div class="contactform contactform-user contactform-user-content">
    <div id="feedback">
        <?= $password->startForm('', word('Восстановление пароля')) ?>
        <?= $password->formError() ?>
        <input name="formid" type="hidden"  value="register" />
        <p class="cmfHide">
            <?= $form->viewError('email') ?>
            <label><span style="color: #ff0000;">*</span> <?= word('Фамилия, имя, отчество') ?></label>
            <?= $form->html('email', 'class=""') ?>
        </p>
        <p>
            <?= $form->viewError('login') ?>
            <label for="email" ><span style="color: #ff0000;">*</span> <?= word('Электронная почта') ?></label>
            <?= $form->html('login', 'class=""') ?>
        </p>
        <p>
            <?= $form->viewError('captcha') ?>
            <label><span style="color: #ff0000;">*</span> <?= word('Код безопасности') ?></label>
            <?= $form->html('captcha', 'class=""') ?>
        </p>
        <p>
            <span class="formwrap-text">
                <?= $password->getForm()->get('captcha')->image() ?><br>
                <a onclick="<?= $form->get('captcha')->jsReloadImage() ?>"><?=word('Обновить код') ?></a>
            </span>
        </p>
        <div class="empty"></div>
        <!--        <div class="captcha">
                    <p>Введите код:</p>
                    <p><img src="/manager/includes/veriword.php?rand=7653" alt="Код проверки" />&nbsp;&nbsp;<span class="formwrap_small"><input class="vericodeform" name="vericode" type="text" value="" /></span></p>
                </div>-->
        <p>
            <input type="submit" value="<?= word('Отправить') ?>" />
            <span>
                <a href="<?= $enterUrl ?>"><?= word('Войти в личный кабинет') ?></a>
                <br><a href="<?= $registerUrl ?>"><?= word('Регистрация') ?></a>
            </span>
        </p>
        <p class="clear"><span style="font-size: 90%;"><?= word('Поля отмеченные') ?> <span style="color: #ff0000;">* </span><?= word('обязательны для заполнения') ?>.</span></p>
        <?= $password->endForm() ?>
    </div>
</div>