<h1 class="h1-bottom"><?= word('Личный кабинет') ?></h1>
<div class="content-info">
    <?= $content ?>
</div>
<? /* ?><p><a href="<?= $infoUrl ?>"><?= word('Личные данные') ?></a></p><?*/ ?>
<p><?= word('Логин') ?>: <?=$user->email ?></p>
<? /*
<p><a href="<?= $boardUrl ?>"><?= word('Добавить объявление') ?></a></p>
<p><a href="<?= $passwordUrl ?>"><?= word('Изменить пароль') ?></a></p>
<p><a href="<?= $exitUrl ?>"><?= word('Выход') ?></a></p>*/ ?>