<?=$slider ?>
<? return ?>



<script type="text/javascript">
            jQuery(document).ready(function($) {
                $('#minimal-slider').advancedSlider({width: 980,
                    height: 400,
                    skin: 'minimal-small',
                    effectType: 'fade',
                    slideEasing: 'easeInOutExpo',
                    overrideTransition: true,
                    keyboardNavigation: true,
                    slideArrows: false,
                    timerAnimation: false,
                    timerStrokeColor1: '#ffffff',
                    timerStrokeColor2: '#000000',
                    timerStrokeOpacity1: 0.3,
                    timerStrokeOpacity2: 0.3,
                    timerStrokeWidth1: 6,
                    timerStrokeWidth2: 3,
                    slideshowDelay: 10000,
                    shadow: false,
                });
            });
        </script>
<div id="nivoslider-wrapper">
    <div id="nivoslider-wrapper-2">
        <div class="advanced-slider" id="minimal-slider">
            <ul class="slides">
                <li class="slide">
                    <img class="image" src="http://bqworks.com/products/advanced-slider/images/v4/large/image1.jpg" alt=""/>
                    <img class="thumbnail" src="http://bqworks.com/products/advanced-slider/images/v4/thumbnails/thumb1.jpg" alt=""/>
                </li>
                <li class="slide">
                    <a class="video" href="http://vimeo.com/43401199">
                        <img src="http://bqworks.com/products/advanced-slider/images/v4/videos/open-education.jpg" width="980" height="400" />
                    </a>
                </li>
                <li class="slide">
                    <img class="image" src="http://bqworks.com/products/advanced-slider/images/v4/videos/unicef.jpg" alt=""/>
                </li>
                <li class="slide">
                    <img class="image" src="http://bqworks.com/products/advanced-slider/images/v4/large/image1.jpg" alt=""/>
                    <img class="thumbnail" src="http://bqworks.com/products/advanced-slider/images/v4/thumbnails/thumb1.jpg" alt=""/>
                </li>
                <li class="slide">
                    <a class="video" href="http://vimeo.com/43401199">
                        <img src="http://bqworks.com/products/advanced-slider/images/v4/videos/open-education.jpg" width="980" height="400" />
                    </a>
                </li>
                <li class="slide">
                    <img class="image" src="http://bqworks.com/products/advanced-slider/images/v4/videos/unicef.jpg" alt=""/>
                </li>
                <li class="slide">
                    <img class="image" src="http://bqworks.com/products/advanced-slider/images/v4/large/image1.jpg" alt=""/>
                    <img class="thumbnail" src="http://bqworks.com/products/advanced-slider/images/v4/thumbnails/thumb1.jpg" alt=""/>
                </li>
                <li class="slide">
                    <a class="video" href="http://vimeo.com/43401199">
                        <img src="http://bqworks.com/products/advanced-slider/images/v4/videos/open-education.jpg" width="980" height="400" />
                    </a>
                </li>
                <li class="slide">
                    <img class="image" src="http://bqworks.com/products/advanced-slider/images/v4/videos/unicef.jpg" alt=""/>
                </li>
            </ul>
        </div>
    </div>
</div>
