<?
view_command::viewLineButton(
        cmfAdminView::buttonType1("modul.postAjax('newLine');", 'Добавить') .
        cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить'))
?>


<?= $main_list->htmlStartForm() ?>
<table class="great_table">
    <tr class="header_col">
        <td width="100px">Сайт</td>
        <td width="40%">Старый адрес</td>
        <td width="40%">Новый адрес</td>
        <td width="22px">Вид</td>
        <td width="22px">Удалить</td>
    </tr>

    <?
    foreach ($main_list as $key => $value) {
        list($form, $data) = $value->main;
        list($formLang, $dataLang) = $value->lang;
        ?>
        <?= view_list::startTR($main_list) ?>
        <td><?= $form->html('type', 'class="width99"') ?></td>
        <td><?= $form->html('url', 'class="width99"') ?></td>
        <td><?= $form->html('new', 'class="width99"') ?></td>
        <td><?= $form->html('visible') ?></td>
        <td>
            <?= $main_list->getHtmlListId(); ?>
            <?= cmfAdminView::onclickType1("modul.deleteAjax(this, '$key');", 'Удалить') ?>
        </td>
    </tr>
<? } ?>
</table>
<?= $main_list->htmlEndForm() ?>

<?
view_command::viewLineButton(
        cmfAdminView::buttonType1("modul.postAjax('newLine');", 'Добавить') .
        cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить'))
?>
