<?
view_command::viewLineButton(
        cmfAdminView::buttonType1("modul.postAjax('newLine');", 'Добавить') .
        cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить'))
?>


<?= $main_list->htmlStartForm() ?>
<table class="great_table">
    <tr class="header_col">
        <td width="22px">#</td>
        <td>Название</td>
        <td width="400px">Изображение</td>
        <td width="22px">Вверху списка</td>
        <td width="22px">Вид</td>
        <td width="22px">Удалить</td>
    </tr>

    <?
    foreach ($main_list as $key => $value) {
        list($form, $data) = $value->main;
        list($formLang, $dataLang) = $value->lang;
        ?>
        <?= view_list::startTR($main_list) ?>
        <?= $main_list->getPostMove($data) ?>
        <td>
            <?= $main_list->langViewTranslate('name') ?>
            <?= $formLang->html('name', 'class="width99"') ?>
        </td>
        <td><?=$main_list->getImageView('main', 'image') ?></td>
        <td><?= $form->html('main') ?></td>
        <td><?= $form->html('visible') ?></td>
        <td>
            <?= $main_list->getHtmlListId(); ?>
            <?= cmfAdminView::onclickType1("modul.deleteAjax(this, '$key');", 'Удалить') ?>
        </td>
    </tr>
<? } ?>
</table>
<?= $main_list->htmlEndForm() ?>

<?
view_command::viewLineButton(
        cmfAdminView::buttonType1("modul.postAjax('newLine');", 'Добавить') .
        cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить'))
?>
