	<table class="table_position">
	<tr class="header_col">
	<td>Раздел: <?=cmfView::selectOncahge($filterSection) ?></td>
	</tr>
	</table>

<?
view_command::viewLineButton(
        cmfAdminView::buttonType1("modul.postAjax('newLine');", 'Добавить') .
        cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить'))
?>


<?= $main_list->htmlStartForm() ?>
<table class="great_table">
    <tr class="header_col">
        <td width="22px">#</td>
        <td width="80px" class="cmfHide">Стиль</td>
        <td width="300px">Меню</td>
        <td>Название</td>
        <td width="22px">Вид</td>
        <td width="22px">Удалить</td>
    </tr>

    <?
    foreach ($main_list as $key => $value) {
        list($form, $data) = $value->main;
        list($formLang, $dataLang) = $value->lang;
        ?>
        <?= view_list::startTR($main_list) ?>
        <?= $main_list->getPostMove($data) ?>
        <td class="cmfHide"><?= $form->html('class', 'class="width99"') ?></td>
        <td><?= $form->html('menu', 'class="width99" onchange="cmf.pages.adress' . $key . '();"') ?></td>
        <td>
            <?= $main_list->langViewTranslate('name') ?>
            <?= $formLang->html('name', 'class="width99"') ?>
            <div id="adress<?= $key ?>"><?= $form->html('url', 'class="width99"') ?></div>
            <script language="JavaScript">
                cmf.pages.adress<?= $key ?> = function() {
                    var value = cmf.getValue('<?= $form->getId('menu') ?>');
                    if(value=='adress') {
                        $('#adress<?= $key ?>').show();
                    } else {
                        $('#adress<?= $key ?>').hide();
                    }
                };
                cmf.pages.adress<?= $key ?>();
            </script>
        </td>
        <td><?= $form->html('visible') ?></td>
        <td>
            <?= $main_list->getHtmlListId(); ?>
            <?= cmfAdminView::onclickType1("modul.deleteAjax(this, '$key');", 'Удалить') ?>
        </td>
    </tr>
<? } ?>
</table>
<?= $main_list->htmlEndForm() ?>

<?
view_command::viewLineButton(
        cmfAdminView::buttonType1("modul.postAjax('newLine');", 'Добавить') .
        cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить'))
?>
