    <? view_command::viewLineButton(
                       cmfAdminView::buttonType2($main_list->getNewUrl(), 'Добавить') .
                       cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>


<?=$main_list->htmlStartForm() ?>
	<table class="great_table">
	<tr class="header_col">
	<td>Название</td>
	<td width="200px">Записи</td>
	<td width="22px">Вид</td>
	<td width="22px">Удалить</td>
	</tr>

<?	foreach($main_list as $key=>$value){
		list($form, $data) = $value->main;
	 ?>
	<?=view_list::startTR($main_list) ?>
	<td><?=cmfAdminView::buttonType3($main_list->getEditUrl(), $data->lang('name')) ?></td>
	<td><?=cmfAdminView::buttonType3($main_list->getBlogUrl(), 'Все Записи ('. $main_list->listAutor($key) .')') ?></td>
	<td><?=$form->html('visible') ?></td>
	<td>
		<?=$main_list->getHtmlListId(); ?>
		<?=cmfAdminView::onclickType1("modul.deleteAjax(this, '$key');", 'Удалить') ?>
	</td>
	</tr>
<? } ?>
	</table>
<?=$main_list->htmlEndForm() ?>

	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType2($main_list->getNewUrl(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>
