
	<table class="table_position">

    <tr class="header_col">
    <!--//<td width="50%">Верфь: <?=cmfView::selectOncahge($filterShipyards, 'class="width99"') ?></td>//-->
    <td width="50%">Тип яхты: <?=cmfView::selectOncahge($filterType, 'class="width99"') ?></td>
	</tr>

	</table>


	<? view_command::viewLimitButton(
						'<td width="120px">Всего яхт: <b>'. $main_list->getTotal() .'</b></td>',
						$limitUrl, $linkPage,
						cmfAdminView::buttonType2($main_list->getNewUrl(), 'Добавить') .
						cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>

<?=$main_list->htmlStartForm() ?>
	<table class="great_table">
	<tr class="header_col">
	<td width="22px">#</td>
	<td width="200px">Верфь /<br />Тип яхты </td>
	<td>Название</td>
	<td width="200px">Постоянная ссылка</td>
	<td width="100px">Цена</td>
	<td width="22px">Витрина</td>
	<td width="22px">Вид</td>
	<td width="22px">Удалить</td>
	</tr>

<?	foreach($main_list as $key=>$value){
		list($form, $data) = $value->main;
		?>
	<?=view_list::startTR($main_list) ?>

	<?=$main_list->getPostMove($data) ?>
	<td><!--//<?=get2($filterShipyards, $data->shipyards, 'name', 'нет') ?>//--><?=$data->lang('shipyardsName', 'по запросу') ?> /
	<br /><?=get2($filterType, $data->type, 'name', 'нет') ?></td>

	<td><? if($key) echo cmfAdminView::buttonType3($main_list->getEditUrl(), $data->lang('name')) ?></td>

	<td><?=$main_list->viewListSiteUrl($filterType, $data) ?></td>
	<td><?=$data->price ?></td>
	<td><?=$form->html('menu') ?></td>
	<td><?=$form->html('visible') ?></td>
	<td>
		<?=$main_list->getHtmlListId(); ?>
		<?=cmfAdminView::onclickType1("modul.deleteAjax(this, '$key');", 'Удалить') ?></td>
	</tr>
<? } ?>
	</table>
<?=$main_list->htmlEndForm() ?>

	<? view_command::viewLimitButton(
						'<td width="120px">Всего яхт: <b>'. $main_list->getTotal() .'</b></td>',
						$limitUrl, $linkPage,
						cmfAdminView::buttonType2($main_list->getNewUrl(), 'Добавить') .
						cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>

