	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("modul.postAjaxSave('update');", 'Сохранить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить') .
	                   cmfAdminView::buttonType2($main_edit->getCatalogUrl(), 'Вернуться')) ?>


<?=$main_edit->htmlStartForm() ?>
<table class="great_table">
<tr class="header_col">
<td colspan="4"><?=$main_edit->viewSiteUrl() ?></td>
</tr>

<tr>
<td class="svet_td">&nbsp;</td>
<td class="svet_td2 selectCheckbox">
    <?=$form->label('main', 'Вверху списка') ?><?=$form->html('main') ?>
    <?=$form->label('visible', 'Отображать') ?><?=$form->html('visible') ?></td>
</tr>

<tr>
<td class="svet_td">Дата:</td>
<td class="svet_td2" id="f_date3">
<?=$form->html('date', 'class="width25" onfocus="cmf.pages.focus(this);"') ?>
<script type="text/javascript">
cmf.pages.cal = Calendar.setup({
	showTime: 24,
	minuteStep: 1,
	onSelect: function(cal) {
		cmf.pages.updateFields(cal);
		cal.hide()
	},
    onTimeChange: function(cal) {
		cmf.pages.updateFields(cal);
	},
});
cmf.pages.focus = function(input) {
	var date = (new RegExp("([0-9]{2})\.([0-9]{2})\.([0-9]{4}) ([0-9]{2})\:([0-9]{2})")).exec(input.value);
	cmf.pages.cal.setHours(date[4]);
	cmf.pages.cal.setMinutes(date[5]);
	date = new Date(date[3], date[2]-1, date[1], date[4], date[5]);
	cmf.pages.cal.selection.set(date)
	cmf.pages.cal.moveTo(date)
	cmf.pages.cal.popup(cmf.getId('datePopup'), 'right');
}
cmf.pages.updateFields = function(cal) {
	var date = cal.selection.get();
	if (date) {
		date = Calendar.intToDate(date);
		date.setHours(cal.getHours());
		date.setMinutes(cal.getMinutes());
		cmf.setValue('<?=$form->getId('date') ?>', Calendar.printDate(date, "%d-%m-%Y %H:%M"));
	}
};
</script>
</td>
</tr>

<tr>
<td class="svet_td">Адрес:</td>
<td class="svet_td2" colspan="3"><?=$form->html('uri', 'class="width50"') ?></td>
</tr>

<tr>
<td class="svet_td">Автор:</td>
<td class="svet_td2" colspan="3"><?=$form->html('autor', 'class="width50"') ?></td>
</tr>

<tr>
<td class="svet_td">Название:</td>
<td class="svet_td2" colspan="3">
    <?=$main_edit->langViewTranslate('name') ?>
    <?=$langForm->html('name', 'class="width99"') ?></td>
</tr>

<tr>
<td class="svet_td">Изображение:</td>
<td class="svet_td2"><?=$main_edit->getImage('main', 'image') ?></td>
</tr>

<tr>
<td class="svet_td">Анонс:</td>
<td class="svet_td2">
    <?=$main_edit->langViewTranslate('name') ?>
    <?=$langForm->html('notice', 200) ?></td>
</tr>

<tr>
<td class="svet_td">Контент:</td>
<td class="svet_td2">
    <?=$main_edit->langViewTranslate('name') ?>
    <?=$langForm->html('content', 400) ?></td>
</tr>

<tr class="header_col">
<td colspan="4">Seo</td>
</tr>
<tr>
<td class="svet_td">title:</td>
<td class="svet_td2" colspan="3">
    <?=$main_edit->langViewTranslate('name') ?>
    <?=$langForm->html('title', 'class="width99" rows="3"') ?></td>
</tr>
<tr>
<td class="svet_td">keywords:</td>
<td class="svet_td2" colspan="3">
     <?=$main_edit->langViewTranslate('name') ?>
     <?=$langForm->html('keywords', 'class="width99" rows="3"') ?></td>
</tr>
<tr>
<td class="svet_td">description:</td>
<td class="svet_td2" colspan="3">
    <?=$main_edit->langViewTranslate('name') ?>
    <?=$langForm->html('description', 'class="width99" rows="3"') ?></td>
</tr>

</table>
<?=$main_edit->htmlEndForm() ?>

	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("modul.postAjaxSave('update');", 'Сохранить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить') .
	                   cmfAdminView::buttonType2($main_edit->getCatalogUrl(), 'Вернуться')) ?>